-- Import av 11 nya bolag (id 48-58) tillagda 2026-08-04 via Excel-mallen.
-- Kör i Supabase SQL Editor.

insert into companies (
  id, name, city, address, lat, lng, auktorisation, focus, services,
  size_band, ka, founded, revenue, revenue_year, employees, employees_year,
  rating, rating_count, vision, description, contact, link, logo
) values
  (48, 'Storesupport Sverige AB', 'Solna', 'Vretenvägen 13, 171 54 Solna; Södra Gubberogatan 8, 416 63 Göteborg', 59.3541279, 17.9743971, ARRAY[]::text[], ARRAY['Försäljning, inköp, marknadsföring','Transport, distribution, lager'], ARRAY['Bemanning','Rekrytering'], 'Litet', true, 2000, '27,5 Mkr', 2024, '27', 2024, 4.5, 28, 'Storesupport erbjuder tjänster som utvecklar och gör detaljhandeln i Sverige effektiv och lönsam.', 'Storesupport är ett bemannings- och rekryteringsföretag inriktat på detaljhandeln, med huvudkontor i Solna och kontor bland annat i Göteborg, som förser svenska handelsföretag med butiks-, lager- och logistikpersonal.', null, 'https://storesupport.se/kontakt/gbg/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRII1tA2r71135ainK4mqwYt0Go_d6FyG8QikBR8NPOZPbAo4TxwFxycfg&s=10'),
  (49, 'Framtiden i Sverige AB', 'Jönköping', 'Borgmästargränd 1D, 553 20 Jönköping; Vädursgatan 5, 412 50 Göteborg', 57.7820335, 14.1724597, ARRAY['Bemanning','Rekrytering'], ARRAY['Administration, ekonomi, juridik','Data/IT'], ARRAY['Bemanning','Rekrytering'], 'Medel', true, 2004, '354,1 Mkr', 2024, '457', 2024, 3.8, 10, 'Vi gör skillnad genom att hjälpa människor att hitta rätt jobb och rätt kollega.', 'Framtiden (Framtiden i Sverige AB) är ett auktoriserat rekryterings- och bemanningsföretag med huvudkontor i Jönköping och kontor på flera orter, däribland Göteborg, som förmedlar personal och rekryterar inom bland annat administration, ekonomi, IT och HR.', 'info@framtiden.com', 'https://www.framtiden.com/goteborg/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoMmB2JDLGKPvwk1LzSD5S8liPDbJ98jahp5IowbP_4w&s=10'),
  (50, 'Amendo Konsult & Rekrytering AB', 'Stockholm', 'Kungsgatan 8, 111 43 Stockholm; Sankt Eriksgatan 6, 411 05 Göteborg', 59.3361679, 18.0696048, ARRAY['Bemanning','Rekrytering'], ARRAY['Administration, ekonomi, juridik','Data/IT'], ARRAY['Bemanning','Rekrytering','Interim'], 'Litet', true, 2001, '81,0 Mkr', 2024, '98', 2024, 3, 2, 'Utveckla världen med kompetens.', 'Amendo är ett auktoriserat rekryterings- och bemanningsföretag med huvudkontor i Stockholm och kontor i bland annat Göteborg, specialiserat på ekonomi, bank, försäkring och IT.', 'info@amendo.se', 'https://www.amendo.se/goteborg/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_vwg5TeH9O9DXLHo4FOaCzUjG_PCl_8mnJYwxe4YROA&s=10'),
  (51, 'RA Hospitality i Göteborg AB', 'Göteborg', 'Södra Vägen 67, 412 54 Göteborg', 57.6972745, 11.9845842, ARRAY['Bemanning','Rekrytering'], ARRAY['Hotell, restaurang, storhushåll'], ARRAY['Bemanning','Rekrytering'], 'Litet', true, 2000, '34,7 Mkr', 2024, '62', 2024, 4.9, 7, 'Vi tror på möten.', 'RA Hospitality i Göteborg AB är ett auktoriserat bemannings- och rekryteringsföretag inom besöksnäringen som förser hotell, restauranger och evenemang i Göteborgsområdet med personal inom servering, kök och kundservice.', 'info@rahospitality.se', 'https://rahospitality.se/kontakt/goteborg/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiaspKFb9vNp9bsedIWUkGrHrP2zTttpSNtHa48e_AyQ&s=10'),
  (52, 'Eventpersonal i Sverige AB', 'Stockholm', 'Roslagsgatan 34, 113 55 Stockholm', 59.348023, 18.0585445, ARRAY[]::text[], ARRAY['Hotell, restaurang, storhushåll','Försäljning, inköp, marknadsföring'], ARRAY['Bemanning'], 'Litet', false, 2007, '15,7 Mkr', 2025, '27', 2025, 1, 1, 'Rätt personal lyfter ditt event.', 'Eventpersonal i Sverige AB förmedlar eventpersonal, demopersonal, mässvärdar och samplingpersonal till företag i Stockholm, Göteborg, Malmö och övriga Sverige.', 'info@eventpersonal.se', 'https://eventpersonal.se/kontakt/', null),
  (53, 'Logent AB', 'Stockholm', 'Flygfältsgatan 14, 423 37 Göteborg; Hammarby Kaj 14, 120 30 Stockholm', 57.7085384, 11.7754406, ARRAY['Bemanning'], ARRAY['Industriell tillverkning','Transport, distribution, lager'], ARRAY['Bemanning','Rekrytering'], 'Stort', true, 2002, '807,1 Mkr', 2024, '543', 2024, null, 0, 'Smarta lösningar. Enkelt.', 'Stockholmsbaserad logistik- och bemanningskoncern med kontor bland annat i Göteborg, som erbjuder lager-, terminal- och personaluthyrningstjänster till industri- och handelskunder.', 'info@logent.se', 'https://logent.se/sv/kontaktformular/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6_JQmPo06xTaQoB0wnqDf_Dg_86-dSqq_LBbSoj7gSQ&s=10'),
  (54, 'NearYou Sverige AB', 'Borås', 'Fabriksgatan 8, 503 38 Borås', 57.7169185, 12.9412311, ARRAY['Bemanning','Rekrytering'], ARRAY['Industriell tillverkning','Transport, distribution, lager'], ARRAY['Bemanning','Rekrytering','Interim'], 'Stort', true, 1993, '700 Mkr (koncern)', 2024, '1 000 (koncern)', 2024, null, 0, 'Vi vill ändra arbetsmarknaden genom att själva vara en del av förändringen varje dag, hela dagen.', 'Borås-baserad bemannings- och rekryteringskoncern med ett 20-tal kontor runt om i Sverige, bland annat i Göteborg och Vårgårda, med fokus på industri, lager och logistik.', 'info@nearyou.se', 'https://nearyou.se/kontakt/', 'https://media.licdn.com/dms/image/v2/D4D0BAQEO8xzxmDurjg/company-logo_200_200/company-logo_200_200/0/1729177731090/nearyourekryteringbemanning_logo?e=2147483647&v=beta&t=AAQVzUAXMJ5en8buzg_BwhX6zWYFtMOrG8-4mFRNVNc'),
  (55, 'Simplex Bemanning AB', 'Stockholm', 'Teatergatan 19, 411 35 Göteborg; Liljeholmsvägen 18, 117 61 Stockholm', 57.698884, 11.9755226, ARRAY['Bemanning'], ARRAY['Transport, distribution, lager'], ARRAY['Bemanning','Rekrytering'], 'Stort', true, 2014, '388,7 Mkr', 2025, '555', 2025, null, 0, 'Vår vision är att förenkla bemanning utan att kompromissa med kvalitet.', 'Stockholmsbaserat bemannings- och rekryteringsföretag med kontor även i Göteborg, Malmö och Eskilstuna, med inriktning mot lager-, logistik- och transportpersonal.', 'info@simplexbemanning.se', 'https://simplexbemanning.se/kontakt/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDp09tJQiHAVJA-l1hh4jg3jDqKM0zPD1J6pmLc3kfFg&s=10'),
  (56, 'PS Partner AB', 'Göteborg', 'Johan Willins Gata 6, 416 64 Göteborg; Kungsgatan 8, 111 43 Stockholm', 57.7086087, 11.9913807, ARRAY[]::text[], ARRAY['Administration, ekonomi, juridik','Data/IT'], ARRAY['Bemanning','Rekrytering','Interim'], 'Litet', false, 2010, '8,6 Mkr', 2024, '5', 2024, null, 0, 'Rätt person på rätt plats, i exakt rätt tid. Det är vår metodik.', 'Göteborgsbaserat rekryterings- och interimsbolag med kontor även i Stockholm, som arbetar med chefs- och specialistrekrytering inom bland annat ekonomi, HR, IT och försäljning.', 'info@pspartner.se', 'https://pspartner.se/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx8ZvFNuoXiAlqoqxn_3243JnJ90tF2ZclqkF9fs5lxQ&s=10'),
  (57, 'Crew 4 You Bemanning Sweden AB', 'Göteborg', 'Kungsgatan 4, 411 19 Göteborg', 57.7028001, 11.9567046, ARRAY[]::text[], ARRAY['Hotell, restaurang, storhushåll'], ARRAY['Bemanning','Rekrytering'], 'Litet', false, 2011, '8,1 Mkr', 2025, '10', 2025, null, 0, 'Ditt personliga bemanningsföretag.', 'Göteborgsbaserat bemannings- och rekryteringsföretag som levererar personal till restaurang, hotell, event och service i bland annat Göteborg och Stockholm.', 'kontakt@crew4you.se', 'https://crew4you.se/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuIy6p-_in2S82iuR6QemZOzSsHOxhpEDIJAIjK4aBcQ&s=10'),
  (58, '55Plus AB', 'Helsingborg', 'Muskötgatan 19, 254 66 Helsingborg', 56.0748664, 12.7210809, ARRAY[]::text[], ARRAY['Sanering och renhållning','Hantverk'], ARRAY['Bemanning'], 'Medel', true, 2009, '146,4 Mkr', 2024, '195', 2024, 4.3, 19, 'Våra nöjda kunder får hjälp med exakt det de vill ha hjälp med för en rimlig summa pengar.', 'Helsingborgsbaserat företag som via ett rikstäckande kontorsnät hyr ut och förmedlar seniorer (55+) för hushållsnära tjänster som städning, trädgårdsarbete och snickeri, samt liknande tjänster till företag.', 'info@55plus.se', 'https://www.55plus.se/', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzCk2UN8k0NzWAsR3AkeluxMIRnDHzHeWR-tH4lqp4gA&s=10')
on conflict (id) do nothing;

