export const COMPANIES = [
  {
    id:1, name:"Jovi Konsult AB", city:"Göteborg",
    address:"Götabergsgatan 20A, 411 34 Göteborg; Hertig Johans gata 10D, 541 30 Skövde",
    lat:57.6996584, lng:11.9715479,
    focus:["Produktion","Verkstad"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2016,
    revenue:"221,2 Mkr", revenueYear:2024,
    employees:"301", employeesYear:2024,
    rating:3.9, ratingCount:37,
    vision:"Vill vara bemanningsföretaget med mest närhet, tillgänglighet och hjärta i Västra Götaland.",
    desc:"Göteborgsbaserat bemannings- och rekryteringsbolag med kunder inom bland annat livsmedelsproduktion och verkstadsindustri.",
    contact:"info@jovikonsult.se", link:"https://www.jovikonsult.se/"
  },
  {
    id:2, name:"StudentConsulting Sweden AB (publ)", city:"Göteborg",
    address:"Lilla Bommen 4B, 411 04 Göteborg; Allégatan 67, 503 37 Borås; Åkerssjövägen 12, Trollhättan (huvudkontor Luleå)",
    lat:57.7119435, lng:11.968313,
    focus:["Produktion","Logistik"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2005,
    revenue:"1 158,1 Mkr", revenueYear:2024,
    employees:"609", employeesYear:2024,
    rating:3.8, ratingCount:13,
    vision:"Meet your future — hjälpa fler människor i jobb hos branschens nöjdaste kunder.",
    desc:"Ett av Skandinaviens större bemannings- och rekryteringsbolag, med lokalkontor i Göteborg och tjänster inom bland annat industri, produktion, transport och logistik.",
    contact:"info@studentconsulting.se", link:"https://www.studentconsulting.com/sv/kontakta-oss/vara-kontor/goteborg/"
  },
  {
    id:3, name:"OnePartnerGroup", city:"Göteborg",
    address:"Nellickevägen 22, Göteborg; Katrinedalsgatan 13, 504 52 Borås; Gesällgatan 1, 541 50 Skövde; Södra Ringgatan 37, Alingsås; Fabriksgatan 4, entré 11, 531 30 Lidköping; Torggatan 12, 534 31 Vara",
    lat:57.6883957, lng:11.9975999,
    focus:["Produktion","Lager","Logistik"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Stort", ka:true,
    founded:2009,
    revenue:"1 997 Mkr (koncern)", revenueYear:2024,
    employees:"2 253 (koncern)", employeesYear:2024,
    rating:4.4, ratingCount:281,
    vision:"Bra kollegor bygger Sverige — fler företag och människor ska få uppleva glädje i arbetet.",
    desc:"Rikstäckande kompetenspartner med lokalt kontor i Göteborg som erbjuder bemanning och rekrytering bland annat inom distribution och produktion.",
    contact:"vxl@onepartnergroup.se", link:"https://www.onepartnergroup.se/kontor/goteborg"
  },
  {
    id:4, name:"WRKFRC Bemanning & Rekrytering AB", city:"Göteborg",
    address:"Arendal Skans 33, 418 79 Göteborg",
    lat:57.6964865, lng:11.8183252,
    focus:["Produktion","Verkstad"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:false,
    founded:2008,
    revenue:"33,4 Mkr", revenueYear:2025,
    employees:"51", employeesYear:2025,
    rating:null, ratingCount:0,
    vision:"Sätta människor i centrum och tillföra kompetens och kraft till svensk industri.",
    desc:"Göteborgsbaserat bolag som levererar bemanning och rekrytering till industriföretag, med möjlighet till outsourcing av hela produktionsmoment.",
    contact:"info@wrkfrc.se", link:"https://www.wrkfrc.se/"
  },
  {
    id:5, name:"Posti (f.d. Aditro Logistics)", city:"Göteborg",
    address:"Stigbergsliden 5, Göteborg; Prognosgatan 1, 504 64 Borås",
    lat:57.6994558, lng:11.9376369,
    focus:["Lager","Logistik"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:1973,
    revenue:"342,0 Mkr", revenueYear:2024,
    employees:"531", employeesYear:2024,
    rating:null, ratingCount:0,
    vision:"Alltid och ansvarsfullt leverera viktiga och betydelsefulla saker till manniskor.",
    desc:"Logistik- och bemanningsbolag med rötter i Dila Logistik (1973), sedan Aditro Logistics. Förvärvades av finska Posti 2020 och bytte varumärke till Posti i mars 2024. Nischat mot lager, plock/pack och industribemanning.",
    contact:"info@posti.se", link:"https://jobs.posti.se/"
  },
  {
    id:6, name:"Lernia Bemanning AB", city:"Göteborg",
    address:"Maskingatan 5, 417 64 Göteborg; Västerlånggatan 17, 503 30 Borås; Staveredsgatan 19, 461 31 Trollhättan; Storgatan 20, 541 30 Skövde; St. Mikaelsgatan 2B, 451 40 Uddevalla",
    lat:57.701398, lng:11.9139781,
    focus:["Produktion","Lager","Verkstad"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:1993,
    revenue:"2 821,6 Mkr", revenueYear:2024,
    employees:"4 842", employeesYear:2024,
    rating:3.2, ratingCount:13,
    vision:"Att leverera Sveriges mest värdeskapande tjänster genom rätt kompetens för kunder och individer.",
    desc:"Ett av Sveriges större auktoriserade bemanningsbolag med kontor i Göteborg, verksamt inom bland annat industri, produktion och lager.",
    contact:"kundservice@lernia.se", link:"https://www.lernia.se/for-arbetsgivare/har-finns-vi/goteborg/"
  },
  {
    id:7, name:"Adecco Sweden AB", city:"Göteborg",
    address:"Torggatan 6, 411 05 Göteborg; Storgatan 50, 461 30 Trollhättan; Stationsgatan 7, Skövde",
    lat:57.7085212, lng:11.9652595,
    focus:["Produktion","Lager","Logistik","Verkstad"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:1992,
    revenue:"1 921,5 Mkr", revenueYear:2024,
    employees:"2 791", employeesYear:2024,
    rating:3.8, ratingCount:4,
    vision:"Making the future work for everyone — skapa en arbetsmarknad som fungerar för alla.",
    desc:"Del av globala Adecco Group, ett av varldens största bemannings- och rekryteringsbolag, med kontor i centrala Göteborg.",
    contact:"goteborg@adecco.se", link:"https://www.adecco.com/sv-se/hitta-kontor/goteborg"
  },
  {
    id:8, name:"Manpower AB", city:"Göteborg",
    address:"Fabrikstorget 1, 412 50 Göteborg; Åsboholmsgatan 6, 504 51 Borås; Drottninggatan 37, 461 32 Trollhättan; Trädgårdsgatan 15, 541 30 Skövde; Kungsgatan 11, 451 30 Uddevalla; Kungsgatan 20-22, 441 30 Alingsås; Åby Arenaväg 8A, 431 62 Mölndal",
    lat:57.7044989, lng:11.9923429,
    focus:["Produktion","Verkstad","Logistik"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:1989,
    revenue:"1 423,4 Mkr", revenueYear:2024,
    employees:"2 870", employeesYear:2024,
    rating:2.9, ratingCount:28,
    vision:"Leda i utvecklingen av innovativa bemanningslösningar som kopplar mänsklig potential till affärsnytta.",
    desc:"Svensk del av globala ManpowerGroup, med lång erfarenhet av bemanning inom industri och tillverkning i Göteborgsregionen.",
    contact:"info@manpower.se", link:"https://www.manpower.se/"
  },
  {
    id:9, name:"Randstad AB", city:"Göteborg",
    address:"Södra Hamngatan 35, 411 14 Göteborg; Västerbrogatan 8A, 503 30 Borås; Nohabgatan 14, 461 53 Trollhättan",
    lat:57.7063032, lng:11.9678902,
    focus:["Produktion","Lager","Logistik","Verkstad"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:1984,
    revenue:"2 513,0 Mkr", revenueYear:2024,
    employees:"2 972", employeesYear:2024,
    rating:4.6, ratingCount:38,
    vision:"Human Forward — hjälpa manniskor nå sin fulla potential och företag växa med rätt kompetens.",
    desc:"Svensk del av nederländska Randstad, ett av världens största bemanningsbolag, med lokalt kontor i centrala Göteborg.",
    contact:"info@randstad.se", link:"https://www.randstad.se/"
  },
  {
    id:10, name:"A-Staffing Construction AB", city:"Hisings Backa",
    address:"Nya Tingstadsgatan 1, 422 44 Hisings Backa",
    lat:57.7315975, lng:11.9811082,
    focus:["Verkstad"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:false,
    founded:2015,
    revenue:"217,9 Mkr", revenueYear:2024,
    employees:"208", employeesYear:2024,
    rating:4.5, ratingCount:6,
    vision:"Rekrytering och bemanning med genuint personligt engagemang.",
    desc:"A-Staffing Construction är specialiserade på personallösningar inom bygg-, anläggnings- och elteknikbranschen, från mindre lokala projekt till stora infrastrukturprojekt som tunnlar och broar.",
    contact:"info@astaffing.se", link:"https://www.astaffing.se/"
  },
  {
    id:11, name:"DFDS Professionals AB", city:"Göteborg",
    address:"Box 8978, 402 74 Göteborg",
    lat:57.7072326, lng:11.9670171,
    focus:["Lager","Logistik"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2020,
    revenue:"138,3 Mkr", revenueYear:2024,
    employees:"124", employeesYear:2023,
    rating:null, ratingCount:0,
    vision:"Hjälper logistik- och industriföretag att hitta kvalificerad personal.",
    desc:"DFDS Professionals är DFDS-koncernens svenska bemannings- och rekryteringsverksamhet inom logistik och industri, med fokus på lager, terminal, hamn och fordonsunderhåll i Göteborgs hamn.",
    contact:"", link:"https://www.dfds.com/sv-se/fraktfarjor-och-logistik/professionals"
  },
  {
    id:12, name:"adacto people AB", city:"Göteborg",
    address:"Pumpgatan 1, Göteborg",
    lat:57.7112025, lng:11.9463267,
    focus:["Logistik"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:false,
    founded:2014,
    revenue:"102,9 Mkr", revenueYear:2024,
    employees:"124", employeesYear:2023,
    rating:3.8, ratingCount:46,
    vision:"Vi ger fler möjligheter.",
    desc:"Adacto People bemannar Västsveriges fordons- och logistiksektor, med särskilt fokus på förare med C- och CE-körkort.",
    contact:"info@adactopeople.se", link:"https://www.adactopeople.se/"
  },
  {
    id:13, name:"LN Personal AB", city:"Västra Frölunda",
    address:"Victor Hasselblads gata 9, Västra Frölunda",
    lat:57.6549848, lng:11.9379618,
    focus:["Produktion","Logistik"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:true,
    founded:2003,
    revenue:"34,9 Mkr", revenueYear:2024,
    employees:"62", employeesYear:2024,
    rating:4.2, ratingCount:17,
    vision:"Med kort varsel bistå våra kunder med kompetent arbetskraft vid förändringar i personalbehovet.",
    desc:"LN Personal är ett lokalt bemannings- och rekryteringsföretag i Högsbo industriområde, verksamt inom logistik/industri, teknik, handel och kontor sedan 2003.",
    contact:"info@lnpersonal.se", link:"https://www.lnpersonal.se/"
  },
  {
    id:14, name:"EHRAB ByggBemanning AB", city:"Göteborg",
    address:"Mässans gata 10, Göteborg",
    lat:57.6980078, lng:11.9870197,
    focus:["Verkstad"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:true,
    founded:2010,
    revenue:"45,6 Mkr", revenueYear:2024,
    employees:"77", employeesYear:2024,
    rating:3.9, ratingCount:11,
    vision:"Levererar kvalitetssäkrad byggbemanning med rätt kompetens, certifikat och kollektivavtal.",
    desc:"EHRAB ByggBemanning levererar kompletta arbetslag med byggkompetens till byggprojekt i Göteborgsregionen, med egen skola (EHRAB-skolan) för utbildning.",
    contact:"", link:"https://www.ehrab.com/"
  },
  {
    id:15, name:"ANGI Bemanning AB", city:"Säve",
    address:"Markbovägen 12 B, Säve",
    lat:57.7985572, lng:11.9145248,
    focus:["Logistik"],
    services:["Bemanning"],
    sizeBand:"Litet", ka:false,
    founded:2013,
    revenue:"35,2 Mkr", revenueYear:2023,
    employees:"24", employeesYear:2023,
    rating:null, ratingCount:0,
    vision:"Bedriver bemannings- och godstransportverksamhet i Göteborgsregionen.",
    desc:"ANGI Bemanning bedriver bemannings- och godstransportverksamhet från Säve utanför Göteborg. Ingen egen webbplats har kunnat verifieras.",
    contact:"", link:""
  },
  {
    id:16, name:"Lundin Bemanning AB", city:"Göteborg",
    address:"Vasagatan 26, 411 24 Göteborg",
    lat:57.698465, lng:11.9672092,
    focus:[],
    services:["Bemanning"],
    sizeBand:"Litet", ka:false,
    founded:2013,
    revenue:"16,8 Mkr", revenueYear:2024,
    employees:"25", employeesYear:2024,
    rating:null, ratingCount:0,
    vision:"Göteborgsbaserat bemanningsföretag inom personaluthyrning.",
    desc:"Lundin Bemanning är ett Göteborgsbaserat bemanningsföretag inom personaluthyrning. Ingen egen webbplats har kunnat verifieras, så exakt bransch-/kundfokus är obekräftat.",
    contact:"", link:""
  },
  {
    id:17, name:"IMW Personal Ringön AB", city:"Göteborg",
    address:"Ringögatan 36, Göteborg",
    lat:57.7205644, lng:11.9628182,
    focus:["Logistik"],
    services:["Bemanning"],
    sizeBand:"Litet", ka:false,
    founded:2001,
    revenue:"14,1 Mkr", revenueYear:2025,
    employees:"26", employeesYear:2025,
    rating:null, ratingCount:0,
    vision:"Ett arbetsfordon kan inte bli stående för att chauffören är sjuk.",
    desc:"IMW Personal är ett Almega-auktoriserat bemanningsföretag (sedan 2008) specialiserat på rekrytering och uthyrning av chaufförer, med bas på Ringön i Göteborg.",
    contact:"info@imwpersonal.se", link:"https://www.imwpersonal.se/"
  },
  {
    id:18, name:"EUSTAFF SWEDEN AB", city:"Hisings Backa",
    address:"Importgatan 20, 422 46 Hisings Backa",
    lat:57.7479692, lng:11.9915134,
    focus:["Produktion","Lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:true,
    founded:2021,
    revenue:"30,0 Mkr", revenueYear:2025,
    employees:"51", employeesYear:2025,
    rating:3.8, ratingCount:17,
    vision:"Vi tror att rätt person på rätt plats kan förändra allt.",
    desc:"Eustaff är ett auktoriserat bemannings- och rekryteringsföretag med internationell arbetskraft, verksamt inom lager/logistik, tillverkning, svets, bygg och montage, med kontor även i Rumänien, Bulgarien, Moldavien och Tjeckien.",
    contact:"info@eustaff.se", link:"https://eustaff.se/"
  },
  {
    id:19, name:"TEMP-TEAM Sverige AB", city:"Göteborg",
    address:"Stampgatan 14, Göteborg",
    lat:57.7077068, lng:11.9787173,
    focus:[],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:false,
    founded:2002,
    revenue:"23,1 Mkr", revenueYear:2024,
    employees:"32", employeesYear:2024,
    rating:4.8, ratingCount:5,
    vision:"Människan i fokus.",
    desc:"Temp-Team är en nordisk rekryterings- och bemanningskoncern (del av danska JuhlerGroup, grundad 1979). Specifikt industrifokus för Göteborgskontoret är inte verifierat.",
    contact:"info@temp-team.se", link:"https://temp-team.se/"
  },
  {
    id:20, name:"Intenso Teknikrekrytering AB", city:"Göteborg",
    address:"Klippan 1 A, 414 51 Göteborg",
    lat:57.6905022, lng:11.9083598,
    focus:["Verkstad"],
    services:["Rekrytering"],
    sizeBand:"Litet", ka:false,
    founded:2008,
    revenue:"15,6 Mkr", revenueYear:2024,
    employees:"6", employeesYear:2024,
    rating:5.0, ratingCount:9,
    vision:"Vår vision är att rekrytering ska vara enkelt.",
    desc:"Intenso Teknikrekrytering är specialiserade på rekrytering och search av chefer och specialister inom teknik och IT, och ingår i samma koncern som Säljpoolen.",
    contact:"cassandra.akerblad@intenso.se", link:"https://www.intenso.se/sv",
    logo:"/logos/intenso-teknikrekrytering.jpg"
  }
];
