export const COMPANIES = [
  {
    id:1, name:"Jovi Konsult AB", city:"Göteborg",
    address:"Götabergsgatan 20A, 411 34 Göteborg; Hertig Johans gata 10D, 541 30 Skövde",
    lat:57.6996584, lng:11.9715479,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2016,
    revenue:"221,2 Mkr", revenueYear:2024,
    employees:"301", employeesYear:2024,
    rating:3.9, ratingCount:37,
    vision:"Vill vara bemanningsföretaget med mest närhet, tillgänglighet och hjärta i Västra Götaland.",
    desc:"Göteborgsbaserat bemannings- och rekryteringsbolag med kunder inom bland annat livsmedelsproduktion och verkstadsindustri.",
    contact:"josef.getachew@jovikonsult.se", link:"https://www.jovikonsult.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgoZiqrJrQwNXrfswdwFqAUTIJ5eZw5o2J7GVj5YkKGw&s=10"
  },
  {
    id:2, name:"StudentConsulting Sweden AB (publ)", city:"Göteborg",
    address:"Lilla Bommen 4B, 411 04 Göteborg; Allégatan 67, 503 37 Borås; Åkerssjövägen 12, Trollhättan (huvudkontor Luleå)",
    lat:57.7119435, lng:11.968313,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2005,
    revenue:"1 158,1 Mkr", revenueYear:2024,
    employees:"609", employeesYear:2024,
    rating:3.8, ratingCount:13,
    vision:"Meet your future — hjälpa fler människor i jobb hos branschens nöjdaste kunder.",
    desc:"Ett av Skandinaviens större bemannings- och rekryteringsbolag, med lokalkontor i Göteborg och tjänster inom bland annat industri, produktion, transport och logistik.",
    contact:"info@studentconsulting.se", link:"https://www.studentconsulting.com/sv/kontakta-oss/vara-kontor/goteborg/",
    logo:"https://media.licdn.com/dms/image/v2/C4D0BAQGAQA4mK97H6A/company-logo_200_200/company-logo_200_200/0/1675863218236/studentconsulting_logo?e=2147483647&v=beta&t=wwvFDodARSbWzxXR9C7-Wg2H9fX3hV3JWaKmiWUh2ww"
  },
  {
    id:3, name:"OnePartnerGroup", city:"Göteborg",
    address:"Nellickevägen 22, Göteborg; Katrinedalsgatan 13, 504 52 Borås; Gesällgatan 1, 541 50 Skövde; Södra Ringgatan 37, Alingsås; Fabriksgatan 4, entré 11, 531 30 Lidköping; Torggatan 12, 534 31 Vara",
    lat:57.6883957, lng:11.9975999,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Stort", ka:true,
    founded:2009,
    revenue:"1 997 Mkr (koncern)", revenueYear:2024,
    employees:"2 253 (koncern)", employeesYear:2024,
    rating:4.4, ratingCount:281,
    vision:"Bra kollegor bygger Sverige — fler företag och människor ska få uppleva glädje i arbetet.",
    desc:"Rikstäckande kompetenspartner med lokalt kontor i Göteborg som erbjuder bemanning och rekrytering bland annat inom distribution och produktion.",
    contact:"vxl@onepartnergroup.se", link:"https://www.onepartnergroup.se/kontor/goteborg",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6fnq2MWWGl_tPS-t6aw8i2Cu9-muRpu7B7Y83yItF2w&s=10"
  },
  {
    id:4, name:"WRKFRC Bemanning & Rekrytering AB", city:"Göteborg",
    address:"Arendal Skans 33, 418 79 Göteborg",
    lat:57.6964865, lng:11.8183252,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:false,
    founded:2008,
    revenue:"33,4 Mkr", revenueYear:2025,
    employees:"51", employeesYear:2025,
    rating:null, ratingCount:0,
    vision:"Sätta människor i centrum och tillföra kompetens och kraft till svensk industri.",
    desc:"Göteborgsbaserat bolag som levererar bemanning och rekrytering till industriföretag, med möjlighet till outsourcing av hela produktionsmoment.",
    contact:"info@wrkfrc.se", link:"https://www.wrkfrc.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgmV5Jh16uzUH_xNKHhCrMvde-YLjBhcjbzbb4OotTCg&s=10"
  },
  {
    id:5, name:"Posti (f.d. Aditro Logistics)", city:"Göteborg",
    address:"Stigbergsliden 5, Göteborg; Prognosgatan 1, 504 64 Borås",
    lat:57.6994558, lng:11.9376369,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:1973,
    revenue:"342,0 Mkr", revenueYear:2024,
    employees:"531", employeesYear:2024,
    rating:null, ratingCount:0,
    vision:"Alltid och ansvarsfullt leverera viktiga och betydelsefulla saker till manniskor.",
    desc:"Logistik- och bemanningsbolag med rötter i Dila Logistik (1973), sedan Aditro Logistics. Förvärvades av finska Posti 2020 och bytte varumärke till Posti i mars 2024. Nischat mot lager, plock/pack och industribemanning.",
    contact:"info@posti.se", link:"https://jobs.posti.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPFcj6bl0Xv9mM1Wiztb61ypheqjAohE-8ERCitVOrPA&s=10"
  },
  {
    id:6, name:"Lernia Bemanning AB", city:"Göteborg",
    address:"Maskingatan 5, 417 64 Göteborg; Västerlånggatan 17, 503 30 Borås; Staveredsgatan 19, 461 31 Trollhättan; Storgatan 20, 541 30 Skövde; St. Mikaelsgatan 2B, 451 40 Uddevalla",
    lat:57.701398, lng:11.9139781,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:1993,
    revenue:"2 821,6 Mkr", revenueYear:2024,
    employees:"4 842", employeesYear:2024,
    rating:3.2, ratingCount:13,
    vision:"Att leverera Sveriges mest värdeskapande tjänster genom rätt kompetens för kunder och individer.",
    desc:"Ett av Sveriges större auktoriserade bemanningsbolag med kontor i Göteborg, verksamt inom bland annat industri, produktion och lager.",
    contact:"kundservice@lernia.se", link:"https://www.lernia.se/for-arbetsgivare/har-finns-vi/goteborg/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnhGlJ7oXn-6v4SO2x43PjCcUr2M4yAFelFfS7d7ZePA&s=10"
  },
  {
    id:7, name:"Adecco Sweden AB", city:"Göteborg",
    address:"Torggatan 6, 411 05 Göteborg; Storgatan 50, 461 30 Trollhättan; Stationsgatan 7, Skövde",
    lat:57.7085212, lng:11.9652595,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:1992,
    revenue:"1 921,5 Mkr", revenueYear:2024,
    employees:"2 791", employeesYear:2024,
    rating:3.8, ratingCount:4,
    vision:"Making the future work for everyone — skapa en arbetsmarknad som fungerar för alla.",
    desc:"Del av globala Adecco Group, ett av varldens största bemannings- och rekryteringsbolag, med kontor i centrala Göteborg.",
    contact:"goteborg@adecco.se", link:"https://www.adecco.com/sv-se/hitta-kontor/goteborg",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBIRcPFLBgv4TZy_wEuWyjWGicSQE2jiYhTrqvFu92YA&s=10"
  },
  {
    id:8, name:"Manpower AB", city:"Göteborg",
    address:"Fabrikstorget 1, 412 50 Göteborg; Åsboholmsgatan 6, 504 51 Borås; Drottninggatan 37, 461 32 Trollhättan; Trädgårdsgatan 15, 541 30 Skövde; Kungsgatan 11, 451 30 Uddevalla; Kungsgatan 20-22, 441 30 Alingsås; Åby Arenaväg 8A, 431 62 Mölndal",
    lat:57.7044989, lng:11.9923429,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:1989,
    revenue:"1 423,4 Mkr", revenueYear:2024,
    employees:"2 870", employeesYear:2024,
    rating:2.9, ratingCount:28,
    vision:"Leda i utvecklingen av innovativa bemanningslösningar som kopplar mänsklig potential till affärsnytta.",
    desc:"Svensk del av globala ManpowerGroup, med lång erfarenhet av bemanning inom industri och tillverkning i Göteborgsregionen.",
    contact:"info@manpower.se", link:"https://www.manpower.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVkeXenM1nY3b5U-W08Bu0zcX8BNgV9KOb1xGo5M5NPA&s=10"
  },
  {
    id:9, name:"Randstad AB", city:"Göteborg",
    address:"Södra Hamngatan 35, 411 14 Göteborg; Västerbrogatan 8A, 503 30 Borås; Nohabgatan 14, 461 53 Trollhättan",
    lat:57.7063032, lng:11.9678902,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:1984,
    revenue:"2 513,0 Mkr", revenueYear:2024,
    employees:"2 972", employeesYear:2024,
    rating:4.6, ratingCount:38,
    vision:"Human Forward — hjälpa manniskor nå sin fulla potential och företag växa med rätt kompetens.",
    desc:"Svensk del av nederländska Randstad, ett av världens största bemanningsbolag, med lokalt kontor i centrala Göteborg.",
    contact:"info@randstad.se", link:"https://www.randstad.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRePgeIwfcTYOMeNOBdIcX1PbPsqomGXnAjUDuZY8X1ZQ&s=10"
  },
  {
    id:10, name:"A-Staffing Construction AB", city:"Hisings Backa",
    address:"Nya Tingstadsgatan 1, 422 44 Hisings Backa",
    lat:57.7315975, lng:11.9811082,
    auktorisation:[],
    focus:["Industriell tillverkning"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:false,
    founded:2015,
    revenue:"217,9 Mkr", revenueYear:2024,
    employees:"208", employeesYear:2024,
    rating:4.5, ratingCount:6,
    vision:"Rekrytering och bemanning med genuint personligt engagemang.",
    desc:"A-Staffing Construction är specialiserade på personallösningar inom bygg-, anläggnings- och elteknikbranschen, från mindre lokala projekt till stora infrastrukturprojekt som tunnlar och broar.",
    contact:"info@astaffing.se", link:"https://www.astaffing.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMG1snD1WQTivkSAoyO3q3s1zpekjotMP84USf7K58CGjo3dODRVfWrS8&s=10"
  },
  {
    id:11, name:"DFDS Professionals AB", city:"Göteborg",
    address:"Box 8978, 402 74 Göteborg",
    lat:57.7072326, lng:11.9670171,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2020,
    revenue:"138,3 Mkr", revenueYear:2024,
    employees:"124", employeesYear:2023,
    rating:null, ratingCount:0,
    vision:"Hjälper logistik- och industriföretag att hitta kvalificerad personal.",
    desc:"DFDS Professionals är DFDS-koncernens svenska bemannings- och rekryteringsverksamhet inom logistik och industri, med fokus på lager, terminal, hamn och fordonsunderhåll i Göteborgs hamn.",
    contact:"", link:"https://www.dfds.com/sv-se/fraktfarjor-och-logistik/professionals",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrlc6aThCaHVAibsCCb0_DGIV96CKs9lJdQD-U5qFicw&s=10"
  },
  {
    id:12, name:"adacto people AB", city:"Göteborg",
    address:"Pumpgatan 1, Göteborg",
    lat:57.7112025, lng:11.9463267,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:false,
    founded:2014,
    revenue:"102,9 Mkr", revenueYear:2024,
    employees:"124", employeesYear:2023,
    rating:3.8, ratingCount:46,
    vision:"Vi ger fler möjligheter.",
    desc:"Adacto People bemannar Västsveriges fordons- och logistiksektor, med särskilt fokus på förare med C- och CE-körkort.",
    contact:"info@adactopeople.se", link:"https://www.adactopeople.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvLiI-eS9Ul1zUTQvpIunWGsssoHeAGHC7AlIXVe1wuQ&s=10"
  },
  {
    id:13, name:"LN Personal AB", city:"Västra Frölunda",
    address:"Victor Hasselblads gata 9, Västra Frölunda",
    lat:57.6549848, lng:11.9379618,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:true,
    founded:2003,
    revenue:"34,9 Mkr", revenueYear:2024,
    employees:"62", employeesYear:2024,
    rating:4.2, ratingCount:17,
    vision:"Med kort varsel bistå våra kunder med kompetent arbetskraft vid förändringar i personalbehovet.",
    desc:"LN Personal är ett lokalt bemannings- och rekryteringsföretag i Högsbo industriområde, verksamt inom logistik/industri, teknik, handel och kontor sedan 2003.",
    contact:"info@lnpersonal.se", link:"https://www.lnpersonal.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLtO_CozDval5-qOHeT1-a6-hnVcDEXMNG5qLKweAehg&s=10"
  },
  {
    id:14, name:"EHRAB ByggBemanning AB", city:"Göteborg",
    address:"Mässans gata 10, Göteborg",
    lat:57.6980078, lng:11.9870197,
    auktorisation:[],
    focus:["Industriell tillverkning"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:true,
    founded:2010,
    revenue:"45,6 Mkr", revenueYear:2024,
    employees:"77", employeesYear:2024,
    rating:3.9, ratingCount:11,
    vision:"Levererar kvalitetssäkrad byggbemanning med rätt kompetens, certifikat och kollektivavtal.",
    desc:"EHRAB ByggBemanning levererar kompletta arbetslag med byggkompetens till byggprojekt i Göteborgsregionen, med egen skola (EHRAB-skolan) för utbildning.",
    contact:"", link:"https://www.ehrab.com/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUSVaEjDyOS1l6wYw3389KZeFyK_hT9t7sXhc-5DV8eA&s=10"
  },
  {
    id:15, name:"ANGI Bemanning AB", city:"Säve",
    address:"Markbovägen 12 B, Säve",
    lat:57.7985572, lng:11.9145248,
    auktorisation:[],
    focus:["Transport, distribution, lager"],
    services:["Bemanning"],
    sizeBand:"Litet", ka:false,
    founded:2013,
    revenue:"35,2 Mkr", revenueYear:2023,
    employees:"24", employeesYear:2023,
    rating:null, ratingCount:0,
    vision:"Bedriver bemannings- och godstransportverksamhet i Göteborgsregionen.",
    desc:"ANGI Bemanning bedriver bemannings- och godstransportverksamhet från Säve utanför Göteborg. Ingen egen webbplats har kunnat verifieras.",
    contact:"", link:""
  },
  {
    id:16, name:"Lundin Bemanning AB", city:"Göteborg",
    address:"Vasagatan 26, 411 24 Göteborg",
    lat:57.698465, lng:11.9672092,
    auktorisation:[],
    focus:[],
    services:["Bemanning"],
    sizeBand:"Litet", ka:false,
    founded:2013,
    revenue:"16,8 Mkr", revenueYear:2024,
    employees:"25", employeesYear:2024,
    rating:null, ratingCount:0,
    vision:"Göteborgsbaserat bemanningsföretag inom personaluthyrning.",
    desc:"Lundin Bemanning är ett Göteborgsbaserat bemanningsföretag inom personaluthyrning. Ingen egen webbplats har kunnat verifieras, så exakt bransch-/kundfokus är obekräftat.",
    contact:"", link:""
  },
  {
    id:17, name:"IMW Personal Ringön AB", city:"Göteborg",
    address:"Ringögatan 36, Göteborg",
    lat:57.7205644, lng:11.9628182,
    auktorisation:["Bemanning"],
    focus:["Transport, distribution, lager"],
    services:["Bemanning"],
    sizeBand:"Litet", ka:false,
    founded:2001,
    revenue:"14,1 Mkr", revenueYear:2025,
    employees:"26", employeesYear:2025,
    rating:null, ratingCount:0,
    vision:"Ett arbetsfordon kan inte bli stående för att chauffören är sjuk.",
    desc:"IMW Personal är ett Almega-auktoriserat bemanningsföretag (sedan 2008) specialiserat på rekrytering och uthyrning av chaufförer, med bas på Ringön i Göteborg.",
    contact:"info@imwpersonal.se", link:"https://www.imwpersonal.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA8wLgOJh1nlt8pKJrZ4ZCBSJ40CfesvmaGpu5Qm2vOA&s=10"
  },
  {
    id:18, name:"EUSTAFF SWEDEN AB", city:"Hisings Backa",
    address:"Importgatan 20, 422 46 Hisings Backa",
    lat:57.7479692, lng:11.9915134,
    auktorisation:["Bemanning"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:true,
    founded:2021,
    revenue:"30,0 Mkr", revenueYear:2025,
    employees:"51", employeesYear:2025,
    rating:3.8, ratingCount:17,
    vision:"Vi tror att rätt person på rätt plats kan förändra allt.",
    desc:"Eustaff är ett auktoriserat bemannings- och rekryteringsföretag med internationell arbetskraft, verksamt inom lager/logistik, tillverkning, svets, bygg och montage, med kontor även i Rumänien, Bulgarien, Moldavien och Tjeckien.",
    contact:"info@eustaff.se", link:"https://eustaff.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlQe74O44tOlxwfM9qf9qFoNkSvGRTiNN-7l-hrQCqgw&s=10"
  },
  {
    id:19, name:"TEMP-TEAM Sverige AB", city:"Göteborg",
    address:"Stampgatan 14, Göteborg",
    lat:57.7077068, lng:11.9787173,
    auktorisation:["Bemanning","Rekrytering"],
    focus:[],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:false,
    founded:2002,
    revenue:"23,1 Mkr", revenueYear:2024,
    employees:"32", employeesYear:2024,
    rating:4.8, ratingCount:5,
    vision:"Människan i fokus.",
    desc:"Temp-Team är en nordisk rekryterings- och bemanningskoncern (del av danska JuhlerGroup, grundad 1979). Specifikt industrifokus för Göteborgskontoret är inte verifierat.",
    contact:"info@temp-team.se", link:"https://temp-team.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXn3W70saEtrKYiRdxUdkkv2kqa-9HSeW86DbEnXE2CA&s=10"
  },
  {
    id:20, name:"Intenso Teknikrekrytering AB", city:"Göteborg",
    address:"Klippan 1 A, 414 51 Göteborg",
    lat:57.6905022, lng:11.9083598,
    auktorisation:[],
    focus:["Industriell tillverkning"],
    services:["Rekrytering"],
    sizeBand:"Litet", ka:false,
    founded:2008,
    revenue:"15,6 Mkr", revenueYear:2024,
    employees:"6", employeesYear:2024,
    rating:5.0, ratingCount:9,
    vision:"Vår vision är att rekrytering ska vara enkelt.",
    desc:"Intenso Teknikrekrytering är specialiserade på rekrytering och search av chefer och specialister inom teknik och IT, och ingår i samma koncern som Säljpoolen.",
    contact:"cassandra.akerblad@intenso.se", link:"https://www.intenso.se/sv",
    logo:"/logos/intenso-teknikrekrytering.jpg"
  },
  {
    id:21, name:"Perido AB", city:"Stockholm",
    address:"Torkel Knutssonsgatan 24, 118 49 Stockholm",
    lat:59.3164412, lng:18.0577571,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Administration, ekonomi, juridik","Data/IT"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2003,
    revenue:"1 672,0 Mkr", revenueYear:2024,
    employees:"227", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Perido vill skapa möjligheter för mötet mellan kund och konsult, med målet att alla ska trivas och vara engagerade på jobbet.",
    desc:"Perido är ett konsult- och rekryteringsföretag som bemannar och rekryterar tjänstemän inom bland annat ekonomi, IT, HR, marknad och kundservice.",
    contact:"info@perido.se", link:"https://perido.se",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD9zTtdoa-IoCfHCVdK1Xw7PSn1A1uyHhc-A19_P3Slw&s=10"
  },
  {
    id:22, name:"Experis AB", city:"Sundbyberg",
    address:"Evenemangsgatan 21-25, 169 79 Solna",
    lat:59.3695284, lng:18.0032557,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Data/IT"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2011,
    revenue:"857,3 Mkr", revenueYear:2024,
    employees:"915", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Experis vill vara kundernas konkurrensfördel genom att kombinera rätt teknisk kompetens med de mjuka förmågor som är svårast att hitta.",
    desc:"Experis, en del av ManpowerGroup, är ett bemannings- och rekryteringsföretag specialiserat på IT-konsulter och digital kompetens.",
    contact:"", link:"https://www.experis.se",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzuOWEGvlRZZMb930QlakuIUCUJDmtAB6pw0wCbE9x7w&s"
  },
  {
    id:23, name:"Akkodis Sweden AB", city:"Solna",
    address:"Svetsarvägen 6, 171 41 Solna",
    lat:59.3596856, lng:17.9786493,
    auktorisation:["Bemanning"],
    focus:["Yrken med teknisk inriktning","Data/IT"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2005,
    revenue:"124,1 Mkr", revenueYear:2024,
    employees:"128", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Akkodis vill tillsammans med sina kunder engineera en smartare framtid genom digital teknik och innovation.",
    desc:"Akkodis Sweden är ett tekniskt konsult- och bemanningsföretag inom digital engineering, elektrifiering och edge-teknik för bland annat fordons-, försvars- och industrisektorn.",
    contact:"", link:"https://www.akkodis.com/en/sweden",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRn-wEUWyrI94b7h34ANAgngzm0p98gy3SGijuEGipnyw&s=10"
  },
  {
    id:24, name:"Uniflex AB", city:"Johanneshov",
    address:"Arenavägen 41, 121 77 Johanneshov",
    lat:59.2944568, lng:18.0799606,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Stort", ka:true,
    founded:2002,
    revenue:"785,5 Mkr", revenueYear:2024,
    employees:"1 183", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Uniflex vision är att vara den bästa partnern och hjälpa företag att växa genom nära samarbete kring bemanning och rekrytering.",
    desc:"Uniflex är ett rikstäckande bemannings- och rekryteringsföretag med närmare 40 kontor som hjälper företag inom bland annat industri, lager och logistik.",
    contact:"info@uniflex.se", link:"https://uniflex.se",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQg3eHoCZP78iz9gHGixg8R5Lv9HNM9EcxRCD0ZbMxcLQ&s=10"
  },
  {
    id:25, name:"Academic Work Sweden AB", city:"Linköping",
    address:"Gamla Tanneforsvägen 92, 582 52 Linköping",
    lat:58.4117399, lng:15.633027,
    auktorisation:["Bemanning"],
    focus:["Data/IT","Administration, ekonomi, juridik"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:1998,
    revenue:"1 117,9 Mkr", revenueYear:2024,
    employees:"376", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Academic Work vill frigöra potentialen hos människor och företag på en arbetsmarknad som ständigt förändras.",
    desc:"Academic Work är ett bemannings- och rekryteringsföretag som matchar studenter och unga akademiker med uppdrag inom bland annat IT, ekonomi och teknik.",
    contact:"info@academicwork.se", link:"https://www.academicwork.se",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFS5Pt16wbccmOEePUSInenyyEhWCbCgFI43NoCJEW2g&s=10"
  },
  {
    id:26, name:"Bravura Sverige AB", city:"Stockholm",
    address:"Hornsbruksgatan 28, 117 34 Stockholm",
    lat:59.3161104, lng:18.0345027,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Försäljning, inköp, marknadsföring","Administration, ekonomi, juridik"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Litet", ka:true,
    founded:2008,
    revenue:"409,2 Mkr", revenueYear:2024,
    employees:"89", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Bravura vill stärka företag genom människor och människor genom anställning, med ambitionen att bli bäst i världen på det de gör.",
    desc:"Bravura är ett bemannings- och rekryteringsföretag som matchar tjänstemän, ofta tidigt i karriären, inom bland annat försäljning, ekonomi och IT.",
    contact:"info@bravura.se", link:"https://www.bravura.se",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn-06UYbYVL5u9tKtjQTYknDgsjvM6XM2euShWO-PcPQ&s"
  },
  {
    id:27, name:"TNG Group AB", city:"Stockholm",
    address:"Kungsgatan 44, 111 35 Stockholm",
    lat:59.335359, lng:18.0623672,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Chefer och verksamhetsledare","Data/IT"],
    services:["Rekrytering","Bemanning","Interim"],
    sizeBand:"Medel", ka:true,
    founded:2004,
    revenue:"110,3 Mkr", revenueYear:2024,
    employees:"153", employeesYear:2024,
    rating:4.7, ratingCount:224,
    vision:"TNG:s vision är att se kompetens ur fler perspektiv, utmana magkänslan och sätta fakta före fördomar i rekryteringsprocessen.",
    desc:"TNG (Talent Navigation Group) är ett rekryterings-, bemannings- och interimsföretag som arbetar med kompetensbaserad och fördomsfri matchning, bland annat inom chefs- och IT-rekrytering.",
    contact:"info@tng.se", link:"https://www.tng.se",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgb17tKOZtahSlQtyMVs_tWiixbH56-SaElEpR0Q1cOXAnn_rAZdC5CHk&s=10"
  },
  {
    id:28, name:"Clevry Sweden AB", city:"Stockholm",
    address:"Sankt Göransgatan 66, 112 34 Stockholm",
    lat:59.3332721, lng:18.0324969,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Administration, ekonomi, juridik","Chefer och verksamhetsledare"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Medel", ka:true,
    founded:2007,
    revenue:"148,2 Mkr", revenueYear:2024,
    employees:"218", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Clevry vill sätta kompetens och mjuka färdigheter i fokus vid rekrytering genom en skills first-ansats.",
    desc:"Clevry Sweden är ett rekryterings- och bemanningsföretag som arbetar med kompetensbaserad, testdriven matchning, personbedömning och interimslösningar.",
    contact:"consultantcare.se@clevry.com", link:"https://www.clevry.com/sv",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNNHICkF-Q987BH82p9KkP84whwFALsXTiwcH9I4Vg8g&s=10"
  },
  {
    id:29, name:"Veteranpoolen AB", city:"Göteborg",
    address:"Norra Hamngatan 4, 411 14 Göteborg",
    lat:57.7063844, lng:11.961304,
    auktorisation:["Bemanning"],
    focus:["Hantverk"],
    services:["Bemanning"],
    sizeBand:"Medel", ka:true,
    founded:2007,
    revenue:"566,9 Mkr", revenueYear:2024,
    employees:"775", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Veteranpoolens vision är att bygga ett bättre Sverige genom veteranernas kunskap och driv.",
    desc:"Veteranpoolen är Sveriges största arbetsgivare för pensionärer och bemannar företag samt privatkunder med hushållsnära tjänster, hantverk och trädgårdsarbete.",
    contact:"", link:"https://veteranpoolen.se",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_SWpdh6GFlyh6xY74TiwSe0prbCMf-yzivdhoQpzokQ&s=10"
  },
  {
    id:30, name:"Dedicare Sverige AB", city:"Stockholm",
    address:"Ringvägen 100, 118 60 Stockholm",
    lat:59.3071843, lng:18.075471,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Hälso- och sjukvård"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:1996,
    revenue:"294,7 Mkr", revenueYear:2024,
    employees:"200", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Dedicares vision är att växa till ett av Europas ledande bemannings- och rekryteringsföretag inom vård, life science och omsorg.",
    desc:"Dedicare Sverige AB är ett bemannings- och rekryteringsföretag som hyr ut och rekryterar läkare, sjuksköterskor och socionomer till vård och omsorg i Sverige.",
    contact:"dedicare@dedicare.se", link:"https://www.dedicare.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBlmsz9GhRXfinUMFVr4bUC4ext6pKW_sdi4pnehPDEw&s=10"
  },
  {
    id:31, name:"LäkarLeasing Sverige AB", city:"Stockholm",
    address:"Norra Stationsgatan 93, 113 64 Stockholm",
    lat:59.3454602, lng:18.0322367,
    auktorisation:[],
    focus:["Hälso- och sjukvård"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:true,
    founded:2005,
    revenue:"354,2 Mkr", revenueYear:2024,
    employees:"85", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"LäkarLeasing grundades med visionen att skapa en flexibel och hållbar arbetsmarknad inom vården, där både patienter och vårdpersonal står i fokus.",
    desc:"LäkarLeasing är ett av Nordens största vårdbemanningsföretag som hyr ut och rekryterar läkare, sjuksköterskor, socionomer och annan vårdpersonal till sjukhus, primärvård och socialtjänst i Sverige och Norge.",
    contact:"hej@lakarleasing.se", link:"https://www.lakarleasing.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLMladxLxE2YmptPROTj3h5jlK7Ek7qEn6yfcCjGk6Gw&s=10"
  },
  {
    id:32, name:"Vårdbemanning Sverige AB", city:"Stockholm",
    address:"Sveavägen 98, 113 50 Stockholm",
    lat:59.3424754, lng:18.0573058,
    auktorisation:[],
    focus:["Hälso- och sjukvård"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:false,
    founded:2014,
    revenue:"692,1 Mkr", revenueYear:2024,
    employees:"159", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Vårdbemanning Sverige sätter den personliga relationen i centrum, med målet att varje konsult och kund alltid ska känna sig nöjd och väl bemött.",
    desc:"Vårdbemanning Sverige AB är ett av Sveriges största vårdbemanningsföretag som förser regioner, kommuner och privata vårdgivare med läkare, sjuksköterskor och annan vårdpersonal.",
    contact:"kontakt@vbsverige.se", link:"https://vbsverige.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqBYxWjxPIzXUa8ZI8zMk0Mv9pqhIIJUSwGj8nafTQvQ&s=10"
  },
  {
    id:33, name:"Professional Consulting Sweden AB", city:"Luleå",
    address:"Nordkalottvägen 1, 972 54 Luleå",
    lat:65.5660724, lng:22.0924246,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Administration, ekonomi, juridik"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:2006,
    revenue:"170,7 Mkr", revenueYear:2023,
    employees:"412", employeesYear:2023,
    rating:null, ratingCount:null,
    vision:"Som en del av StudentConsulting är målet att vara Skandinaviens ledande bemannings-, uthyrnings- och rekryteringsföretag för studenter, akademiker och yrkesverksamma.",
    desc:"Professional Consulting Sweden AB är ett bemannings- och rekryteringsföretag inom StudentConsulting-koncernen, specialiserat på att hyra ut och rekrytera heltidspersonal, med särskilt fokus på nyexaminerade.",
    contact:"", link:"https://www.studentconsulting.com/"
  },
  {
    id:34, name:"Wise Professionals Konsult AB", city:"Stockholm",
    address:"Linnégatan 87, 115 23 Stockholm",
    lat:59.3347127, lng:18.0950715,
    auktorisation:[],
    focus:["Administration, ekonomi, juridik","Chefer och verksamhetsledare"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:true,
    founded:2001,
    revenue:"164,8 Mkr", revenueYear:2025,
    employees:"89", employeesYear:2025,
    rating:null, ratingCount:null,
    vision:"Wise vision är att leda vägen mot en arbetsmarknad där varje individ känner sig sedd och rustad att nå sin fulla potential i arbetslivet.",
    desc:"Wise Professionals är ett rekryterings- och konsultbemanningsföretag specialiserat på kompetens inom HR, ekonomi, marknadsföring, försäljning och ledarskap.",
    contact:"info@wise.se", link:"https://www.wise.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2Ty-6PGfcKNTgzt5fkideRKzuUf5rAB3IX8UGNwy63w&s"
  },
  {
    id:35, name:"SJR in Sweden AB", city:"Stockholm",
    address:"Humlegårdsgatan 20, 114 46 Stockholm",
    lat:59.3368854, lng:18.0747907,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Administration, ekonomi, juridik"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Medel", ka:true,
    founded:1993,
    revenue:"441,6 Mkr", revenueYear:2025,
    employees:"249", employeesYear:2025,
    rating:null, ratingCount:null,
    vision:"SJR:s vision är att vara det självklara valet för proffs genom hela karriären, genom långsiktiga och förtroendefulla relationer.",
    desc:"SJR är ett svenskt konsult- och rekryteringsföretag specialiserat på ekonomikompetens, som erbjuder bemanning, interimslösningar, rekrytering, executive search och rådgivning.",
    contact:"", link:"https://sjr.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpjPBGNopXlbHceN-i9_74g7DtaaRd-wLXKyxN50da3g&s=10"
  },
  {
    id:36, name:"Meritmind Aktiebolag", city:"Stockholm",
    address:"Sveavägen 17, 111 57 Stockholm",
    lat:59.3340255, lng:18.0644709,
    auktorisation:[],
    focus:["Administration, ekonomi, juridik"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2000,
    revenue:"319,7 Mkr", revenueYear:2024,
    employees:"155", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Meritminds syfte är att hjälpa människor och företag att lyckas, utifrån en \"3 Happy\"-filosofi där kunden, konsulten/kandidaten och Meritmind alla ska vara nöjda.",
    desc:"Meritmind är ett specialistbolag inom konsult-, bemannings- och rekryteringstjänster inom ekonomi, redovisning och juridik.",
    contact:"info@meritmind.se", link:"https://meritmind.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBKs2UnPFJKTVYGybBlqiQA62CxQROuYKCCm2bc8fkHQ&s=10"
  },
  {
    id:37, name:"Jurek Recruitment & Consulting AB", city:"Stockholm",
    address:"Biblioteksgatan 11, 111 46 Stockholm",
    lat:59.3353811, lng:18.0725311,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Administration, ekonomi, juridik","Försäljning, inköp, marknadsföring"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Litet", ka:true,
    founded:2006,
    revenue:"349,5 Mkr", revenueYear:2024,
    employees:"63", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Jureks vision är att bli det ledande bolaget inom sin bransch och nisch, drivet framför allt av nöjda kunder och kandidater.",
    desc:"Jurek är ett rekryterings- och konsultbolag specialiserat på bemanning och rekrytering inom juridik, ekonomi, bank, HR, marknadsföring och affärsstöd.",
    contact:"info@jurek.se", link:"https://jurek.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL8ZH8-xCwUoqJGaKdaGWeNgJ3RZznNE-_ysHSBWV0FA&s=10"
  },
  {
    id:38, name:"Gazella AB", city:"Stockholm",
    address:"Västra Järnvägsgatan 23, 111 64 Stockholm",
    lat:59.332431, lng:18.0527154,
    auktorisation:[],
    focus:["Administration, ekonomi, juridik"],
    services:["Rekrytering","Interim"],
    sizeBand:"Litet", ka:false,
    founded:2014,
    revenue:"226,0 Mkr", revenueYear:2024,
    employees:"103", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Gazellas vision är att vara den naturliga interims- och rekryteringspartnern för ekonomer i Stockholmsregionen genom hela karriären.",
    desc:"Gazella AB är ett rekryterings- och interimsbemanningsföretag specialiserat på ekonomer och finansproffs i Stockholmsregionen.",
    contact:"info@gazella.se", link:"https://www.gazella.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx7vVdcLEt-DPPYA42DNgNtpwLIZA2JsWEcdeC5IbqqQ&s=10"
  },
  {
    id:39, name:"Novare Executive Search Aktiebolag", city:"Stockholm",
    address:"Blasieholmsgatan 4B, 111 48 Stockholm",
    lat:59.3301239, lng:18.0765993,
    auktorisation:[],
    focus:["Chefer och verksamhetsledare"],
    services:["Rekrytering","Interim"],
    sizeBand:"Litet", ka:false,
    founded:2001,
    revenue:"128,4 Mkr", revenueYear:2024,
    employees:"64", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Novare hjälper ägare och styrelser att identifiera den ledare som bäst driver affärstillväxt och organisationsutveckling, för att säkra organisationens framtida framgång.",
    desc:"Novare Executive Search är en av Sveriges ledande executive search-firmor som rekryterar vd:ar, chefer och styrelsemedlemmar till privat och offentlig sektor.",
    contact:"", link:"https://novare.se/executive-search/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-WuiQSfQqx1EQSO6YSPg1awoTdGlx6hODGqjzOvjsdA&s=10"
  },
  {
    id:40, name:"Egon Zehnder Sweden AB", city:"Malmö",
    address:"Lilla Varvsgatan 14, 211 15 Malmö",
    lat:55.6130222, lng:12.9764467,
    auktorisation:[],
    focus:["Chefer och verksamhetsledare"],
    services:["Rekrytering"],
    sizeBand:"Litet", ka:false,
    founded:2013,
    revenue:"181,2 Mkr", revenueYear:2024,
    employees:"1", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Egon Zehnders syfte är att förbättra karriärer och affärsstrategier världen över genom ledarskapsrådgivning och executive search.",
    desc:"Egon Zehnder Sweden AB är den svenska delen av den globala executive search- och ledarskapsrådgivningsfirman Egon Zehnder, med kontor i Stockholm och Malmö.",
    contact:"sweden.reception@egonzehnder.com", link:"https://www.egonzehnder.com/office/sweden",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS34mejZP8xML5lyXgAGWQbX7HqX3VzUq3fm_UU2bQMQw&s=10"
  },
  {
    id:41, name:"Alumni AB", city:"Stockholm",
    address:"Kungsbron 1D, 111 22 Stockholm",
    lat:59.3331702, lng:18.0544152,
    auktorisation:[],
    focus:["Chefer och verksamhetsledare"],
    services:["Rekrytering","Interim"],
    sizeBand:"Litet", ka:false,
    founded:1991,
    revenue:"212,5 Mkr", revenueYear:2024,
    employees:"81", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Alumnis vision är att skapa hållbar påverkan på näringsliv och samhälle, med uppdraget att hjälpa kunder förverkliga sina strategier genom människor.",
    desc:"Alumni AB är en Stockholmsbaserad ledarskapsrådgivningsfirma som erbjuder executive search, interim management, ledarbedömning och utveckling, en del av Alumni Global-koncernen.",
    contact:"info@alumniglobal.com", link:"https://alumniglobal.com/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTq5H0WqDtNIXSXwdUSvThGI69jlo3MR-1NxGk-xJ9HMw&s=10"
  },
  {
    id:42, name:"Clockwork Bemanning & Rekrytering AB", city:"Falun",
    address:"Holmgatan 22, 791 71 Falun",
    lat:60.6062663, lng:15.6312602,
    auktorisation:[],
    focus:["Industriell tillverkning","Pedagogik"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Medel", ka:true,
    founded:2012,
    revenue:"148,3 Mkr", revenueYear:2024,
    employees:"158", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Clockworks uppdrag är att se flera möjligheter hos varje individ, situation, uppdrag och relation, med mottot \"People, Passion, Power!\"",
    desc:"Clockwork Bemanning & Rekrytering AB är ett rikstäckande bemannings- och rekryteringsföretag inom industri och tjänstemannayrken, skolbemanning och rekrytering, med fler än 20 kontor.",
    contact:"hej@clwork.se", link:"https://clockworkpeople.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU5QfGQGm9xh5fMTFLiU0F0zVaQMRSZjcKTpzhEl5wJg&s=10"
  },
  {
    id:43, name:"Wikan Personal AB", city:"Kristianstad",
    address:"Lasarettsboulevarden 2H, 290 32 Kristianstad",
    lat:56.0316423, lng:14.1636505,
    auktorisation:[],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2011,
    revenue:"172,4 Mkr", revenueYear:2025,
    employees:"264", employeesYear:2025,
    rating:null, ratingCount:null,
    vision:"Wikan grundades med ambitionen att vara det kvalitetsledande bemannings- och rekryteringsföretaget, byggt på stark lokal närvaro på varje kontor.",
    desc:"Wikan Personal AB är ett regionalt bemannings- och rekryteringsföretag med ett 16-tal lokala kontor, med fokus främst på industri, teknik och logistik.",
    contact:"", link:"https://wikan.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVVSWmXT-56lTRDD8cX4PMB2EJ0zUmFwChoNsaGrHCmg&s"
  },
  {
    id:44, name:"Montico HR Partner AB", city:"Tranås",
    address:"Västra Vägen 14, 573 41 Tranås",
    lat:58.0433081, lng:14.9740959,
    auktorisation:[],
    focus:["Industriell tillverkning","Bygg och anläggning"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:1999,
    revenue:"306,9 Mkr", revenueYear:2024,
    employees:"474", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Montico utvecklar löpande sin verksamhet, sina medarbetare och sitt erbjudande för att skapa kvalitet i varje del av verksamheten, då kvalitet i tjänsten är den viktigaste framgångsfaktorn för kundnöjdhet.",
    desc:"Montico HR Partner AB är ett bemannings-, rekryterings- och omställningsföretag med huvudkontor i Tranås och ett tjugotal kontor i södra och mellersta Sverige.",
    contact:"info@montico.se", link:"https://www.montico.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLxNzoQP8CEWXGoWQr5bWypcP7JeDtKGHs4FEKeHzqOQ&s=10"
  },
  {
    id:45, name:"Konsultia AB", city:"Umeå",
    address:"Östra Strandgatan 26A, 903 33 Umeå",
    lat:63.8209563, lng:20.2813659,
    auktorisation:[],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2013,
    revenue:"499,1 Mkr", revenueYear:2024,
    employees:"820", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Konsultias vision är att bli Sveriges ledande bemannings- och rekryteringsföretag inom industri, teknik och logistik.",
    desc:"Konsultia AB är ett bemannings- och rekryteringsföretag i norra Sverige specialiserat på verkstadsindustri, trä, elektronik, fordon, processindustri och logistik, med huvudkontor i Umeå.",
    contact:"info@konsultia.se", link:"https://www.konsultia.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPVDzWEzo5aS0QDGIqiKoNsLgTaUuxPtNiajZxoX4WQg&s=10"
  },
  {
    id:46, name:"Nr.1 Personalpartner AB", city:"Borås",
    address:"Bäckeskogsgatan 2, 504 68 Borås",
    lat:57.7278883, lng:12.9350651,
    auktorisation:[],
    focus:["Industriell tillverkning","Bygg och anläggning"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2001,
    revenue:"112,1 Mkr", revenueYear:2025,
    employees:"265", employeesYear:2025,
    rating:null, ratingCount:null,
    vision:"Under varumärket First Personalpartner: \"Vi bygger framtiden inom industrin!\" — med människan och personalen i centrum för verksamheten.",
    desc:"Nr.1 Personalpartner AB, som verkar under varumärket First Personalpartner, är ett Boråsbaserat bemannings- och rekryteringsföretag specialiserat på industri och bygg, med kontor i Borås, Varberg, Halmstad och Skövde.",
    contact:"info@firstpersonal.se", link:"https://firstpersonal.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtOCl6ar9aBs5w9YGcc95QgsM9rqHNb61I8l4rocPzAw&s=10"
  },
  {
    id:47, name:"Fasticon Kompetens AB", city:"Stockholm",
    address:"Gamla Brogatan 32, 111 20 Stockholm",
    lat:59.3337492, lng:18.0589789,
    auktorisation:[],
    focus:["Bygg och anläggning","Installation, drift, underhåll"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Litet", ka:true,
    founded:2007,
    revenue:"173,9 Mkr", revenueYear:2024,
    employees:"42", employeesYear:2024,
    rating:null, ratingCount:null,
    vision:"Fasticon vill vara den marknadsledande specialisten på kompetensförsörjning inom fastighetsrelaterad kompetens, och hjälpa kunder stärka sina organisationer genom att attrahera, utveckla och behålla rätt talanger.",
    desc:"Fasticon Kompetens AB är ett Stockholmsbaserat nischbemannings- och rekryteringsföretag som uteslutande arbetar med fastighetsrelaterade roller, med cirka 200 kunder per år från kontor i Stockholm, Göteborg och Malmö.",
    contact:"info@fasticon.se", link:"https://fasticon.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9R4SNHqVq7nzksMgNZGMakwXt9CszdO7GO63cir6sZQ&s=10"
  },
  {
    id:48, name:"Storesupport Sverige AB", city:"Solna",
    address:"Vretenvägen 13, 171 54 Solna; Södra Gubberogatan 8, 416 63 Göteborg",
    lat:59.3541279, lng:17.9743971,
    auktorisation:[],
    focus:["Försäljning, inköp, marknadsföring","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:true,
    founded:2000,
    revenue:"27,5 Mkr", revenueYear:2024,
    employees:"27", employeesYear:2024,
    rating:4.5, ratingCount:28,
    vision:"Storesupport erbjuder tjänster som utvecklar och gör detaljhandeln i Sverige effektiv och lönsam.",
    desc:"Storesupport är ett bemannings- och rekryteringsföretag inriktat på detaljhandeln, med huvudkontor i Solna och kontor bland annat i Göteborg, som förser svenska handelsföretag med butiks-, lager- och logistikpersonal.",
    link:"https://storesupport.se/kontakt/gbg/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRII1tA2r71135ainK4mqwYt0Go_d6FyG8QikBR8NPOZPbAo4TxwFxycfg&s=10"
  },
  {
    id:49, name:"Framtiden i Sverige AB", city:"Jönköping",
    address:"Borgmästargränd 1D, 553 20 Jönköping; Vädursgatan 5, 412 50 Göteborg",
    lat:57.7820335, lng:14.1724597,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Administration, ekonomi, juridik","Data/IT"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Medel", ka:true,
    founded:2004,
    revenue:"354,1 Mkr", revenueYear:2024,
    employees:"457", employeesYear:2024,
    rating:3.8, ratingCount:10,
    vision:"Vi gör skillnad genom att hjälpa människor att hitta rätt jobb och rätt kollega.",
    desc:"Framtiden (Framtiden i Sverige AB) är ett auktoriserat rekryterings- och bemanningsföretag med huvudkontor i Jönköping och kontor på flera orter, däribland Göteborg, som förmedlar personal och rekryterar inom bland annat administration, ekonomi, IT och HR.",
    contact:"info@framtiden.com", link:"https://www.framtiden.com/goteborg/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoMmB2JDLGKPvwk1LzSD5S8liPDbJ98jahp5IowbP_4w&s=10"
  },
  {
    id:50, name:"Amendo Konsult & Rekrytering AB", city:"Stockholm",
    address:"Kungsgatan 8, 111 43 Stockholm; Sankt Eriksgatan 6, 411 05 Göteborg",
    lat:59.3361679, lng:18.0696048,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Administration, ekonomi, juridik","Data/IT"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Litet", ka:true,
    founded:2001,
    revenue:"81,0 Mkr", revenueYear:2024,
    employees:"98", employeesYear:2024,
    rating:3.0, ratingCount:2,
    vision:"Utveckla världen med kompetens.",
    desc:"Amendo är ett auktoriserat rekryterings- och bemanningsföretag med huvudkontor i Stockholm och kontor i bland annat Göteborg, specialiserat på ekonomi, bank, försäkring och IT.",
    contact:"info@amendo.se", link:"https://www.amendo.se/goteborg/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_vwg5TeH9O9DXLHo4FOaCzUjG_PCl_8mnJYwxe4YROA&s=10"
  },
  {
    id:51, name:"RA Hospitality i Göteborg AB", city:"Göteborg",
    address:"Södra Vägen 67, 412 54 Göteborg",
    lat:57.6972745, lng:11.9845842,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Hotell, restaurang, storhushåll"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:true,
    founded:2000,
    revenue:"34,7 Mkr", revenueYear:2024,
    employees:"62", employeesYear:2024,
    rating:4.9, ratingCount:7,
    vision:"Vi tror på möten.",
    desc:"RA Hospitality i Göteborg AB är ett auktoriserat bemannings- och rekryteringsföretag inom besöksnäringen som förser hotell, restauranger och evenemang i Göteborgsområdet med personal inom servering, kök och kundservice.",
    contact:"info@rahospitality.se", link:"https://rahospitality.se/kontakt/goteborg/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiaspKFb9vNp9bsedIWUkGrHrP2zTttpSNtHa48e_AyQ&s=10"
  },
  {
    id:52, name:"Eventpersonal i Sverige AB", city:"Stockholm",
    address:"Roslagsgatan 34, 113 55 Stockholm",
    lat:59.3480230, lng:18.0585445,
    auktorisation:[],
    focus:["Hotell, restaurang, storhushåll","Försäljning, inköp, marknadsföring"],
    services:["Bemanning"],
    sizeBand:"Litet", ka:false,
    founded:2007,
    revenue:"15,7 Mkr", revenueYear:2025,
    employees:"27", employeesYear:2025,
    rating:1.0, ratingCount:1,
    vision:"Rätt personal lyfter ditt event.",
    desc:"Eventpersonal i Sverige AB förmedlar eventpersonal, demopersonal, mässvärdar och samplingpersonal till företag i Stockholm, Göteborg, Malmö och övriga Sverige.",
    contact:"info@eventpersonal.se", link:"https://eventpersonal.se/kontakt/"
  },
  {
    id:53, name:"Logent AB", city:"Stockholm",
    address:"Flygfältsgatan 14, 423 37 Göteborg; Hammarby Kaj 14, 120 30 Stockholm",
    lat:57.7085384, lng:11.7754406,
    auktorisation:["Bemanning"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:2002,
    revenue:"807,1 Mkr", revenueYear:2024,
    employees:"543", employeesYear:2024,
    rating:null, ratingCount:0,
    vision:"Smarta lösningar. Enkelt.",
    desc:"Stockholmsbaserad logistik- och bemanningskoncern med kontor bland annat i Göteborg, som erbjuder lager-, terminal- och personaluthyrningstjänster till industri- och handelskunder.",
    contact:"info@logent.se", link:"https://logent.se/sv/kontaktformular/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6_JQmPo06xTaQoB0wnqDf_Dg_86-dSqq_LBbSoj7gSQ&s=10"
  },
  {
    id:54, name:"NearYou Sverige AB", city:"Borås",
    address:"Fabriksgatan 8, 503 38 Borås",
    lat:57.7169185, lng:12.9412311,
    auktorisation:["Bemanning","Rekrytering"],
    focus:["Industriell tillverkning","Transport, distribution, lager"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Stort", ka:true,
    founded:1993,
    revenue:"700 Mkr (koncern)", revenueYear:2024,
    employees:"1 000 (koncern)", employeesYear:2024,
    rating:null, ratingCount:0,
    vision:"Vi vill ändra arbetsmarknaden genom att själva vara en del av förändringen varje dag, hela dagen.",
    desc:"Borås-baserad bemannings- och rekryteringskoncern med ett 20-tal kontor runt om i Sverige, bland annat i Göteborg och Vårgårda, med fokus på industri, lager och logistik.",
    contact:"info@nearyou.se", link:"https://nearyou.se/kontakt/",
    logo:"https://media.licdn.com/dms/image/v2/D4D0BAQEO8xzxmDurjg/company-logo_200_200/company-logo_200_200/0/1729177731090/nearyourekryteringbemanning_logo?e=2147483647&v=beta&t=AAQVzUAXMJ5en8buzg_BwhX6zWYFtMOrG8-4mFRNVNc"
  },
  {
    id:55, name:"Simplex Bemanning AB", city:"Stockholm",
    address:"Teatergatan 19, 411 35 Göteborg; Liljeholmsvägen 18, 117 61 Stockholm",
    lat:57.6988840, lng:11.9755226,
    auktorisation:["Bemanning"],
    focus:["Transport, distribution, lager"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Stort", ka:true,
    founded:2014,
    revenue:"388,7 Mkr", revenueYear:2025,
    employees:"555", employeesYear:2025,
    rating:null, ratingCount:0,
    vision:"Vår vision är att förenkla bemanning utan att kompromissa med kvalitet.",
    desc:"Stockholmsbaserat bemannings- och rekryteringsföretag med kontor även i Göteborg, Malmö och Eskilstuna, med inriktning mot lager-, logistik- och transportpersonal.",
    contact:"info@simplexbemanning.se", link:"https://simplexbemanning.se/kontakt/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDp09tJQiHAVJA-l1hh4jg3jDqKM0zPD1J6pmLc3kfFg&s=10"
  },
  {
    id:56, name:"PS Partner AB", city:"Göteborg",
    address:"Johan Willins Gata 6, 416 64 Göteborg; Kungsgatan 8, 111 43 Stockholm",
    lat:57.7086087, lng:11.9913807,
    auktorisation:[],
    focus:["Administration, ekonomi, juridik","Data/IT"],
    services:["Bemanning","Rekrytering","Interim"],
    sizeBand:"Litet", ka:false,
    founded:2010,
    revenue:"8,6 Mkr", revenueYear:2024,
    employees:"5", employeesYear:2024,
    rating:null, ratingCount:0,
    vision:"Rätt person på rätt plats, i exakt rätt tid. Det är vår metodik.",
    desc:"Göteborgsbaserat rekryterings- och interimsbolag med kontor även i Stockholm, som arbetar med chefs- och specialistrekrytering inom bland annat ekonomi, HR, IT och försäljning.",
    contact:"info@pspartner.se", link:"https://pspartner.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx8ZvFNuoXiAlqoqxn_3243JnJ90tF2ZclqkF9fs5lxQ&s=10"
  },
  {
    id:57, name:"Crew 4 You Bemanning Sweden AB", city:"Göteborg",
    address:"Kungsgatan 4, 411 19 Göteborg",
    lat:57.7028001, lng:11.9567046,
    auktorisation:[],
    focus:["Hotell, restaurang, storhushåll"],
    services:["Bemanning","Rekrytering"],
    sizeBand:"Litet", ka:false,
    founded:2011,
    revenue:"8,1 Mkr", revenueYear:2025,
    employees:"10", employeesYear:2025,
    rating:null, ratingCount:0,
    vision:"Ditt personliga bemanningsföretag.",
    desc:"Göteborgsbaserat bemannings- och rekryteringsföretag som levererar personal till restaurang, hotell, event och service i bland annat Göteborg och Stockholm.",
    contact:"kontakt@crew4you.se", link:"https://crew4you.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuIy6p-_in2S82iuR6QemZOzSsHOxhpEDIJAIjK4aBcQ&s=10"
  },
  {
    id:58, name:"55Plus AB", city:"Helsingborg",
    address:"Muskötgatan 19, 254 66 Helsingborg",
    lat:56.0748664, lng:12.7210809,
    auktorisation:[],
    focus:["Sanering och renhållning","Hantverk"],
    services:["Bemanning"],
    sizeBand:"Medel", ka:true,
    founded:2009,
    revenue:"146,4 Mkr", revenueYear:2024,
    employees:"195", employeesYear:2024,
    rating:4.3, ratingCount:19,
    vision:"Våra nöjda kunder får hjälp med exakt det de vill ha hjälp med för en rimlig summa pengar.",
    desc:"Helsingborgsbaserat företag som via ett rikstäckande kontorsnät hyr ut och förmedlar seniorer (55+) för hushållsnära tjänster som städning, trädgårdsarbete och snickeri, samt liknande tjänster till företag.",
    contact:"info@55plus.se", link:"https://www.55plus.se/",
    logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzCk2UN8k0NzWAsR3AkeluxMIRnDHzHeWR-tH4lqp4gA&s=10"
  }
];