// Sveriges 21 län med samtliga 290 kommuner (Region Gotland räknas som en kommun)
export const REGION_MAP = {
  "Blekinge län": ["Karlshamn","Karlskrona","Olofström","Ronneby","Sölvesborg"],
  "Dalarnas län": ["Avesta","Borlänge","Falun","Gagnef","Hedemora","Leksand","Ludvika","Malung-Sälen","Mora","Orsa","Rättvik","Smedjebacken","Säter","Vansbro","Älvdalen"],
  "Gotlands län": ["Gotland"],
  "Gävleborgs län": ["Bollnäs","Gävle","Hofors","Hudiksvall","Ljusdal","Nordanstig","Ockelbo","Ovanåker","Sandviken","Söderhamn"],
  "Hallands län": ["Falkenberg","Halmstad","Hylte","Kungsbacka","Laholm","Varberg"],
  "Jämtlands län": ["Berg","Bräcke","Härjedalen","Krokom","Ragunda","Strömsund","Åre","Östersund"],
  "Jönköpings län": ["Aneby","Eksjö","Gislaved","Gnosjö","Habo","Jönköping","Mullsjö","Nässjö","Sävsjö","Tranås","Vaggeryd","Vetlanda","Värnamo"],
  "Kalmar län": ["Borgholm","Emmaboda","Hultsfred","Högsby","Kalmar","Mönsterås","Mörbylånga","Nybro","Oskarshamn","Torsås","Vimmerby","Västervik"],
  "Kronobergs län": ["Alvesta","Lessebo","Ljungby","Markaryd","Tingsryd","Uppvidinge","Växjö","Älmhult"],
  "Norrbottens län": ["Arjeplog","Arvidsjaur","Boden","Gällivare","Haparanda","Jokkmokk","Kalix","Kiruna","Luleå","Pajala","Piteå","Älvsbyn","Överkalix","Övertorneå"],
  "Skåne län": ["Bjuv","Bromölla","Burlöv","Båstad","Eslöv","Helsingborg","Hässleholm","Höganäs","Hörby","Höör","Klippan","Kristianstad","Kävlinge","Landskrona","Lomma","Lund","Malmö","Osby","Perstorp","Simrishamn","Sjöbo","Skurup","Staffanstorp","Svalöv","Svedala","Tomelilla","Trelleborg","Vellinge","Ystad","Åstorp","Ängelholm","Örkelljunga","Östra Göinge"],
  "Stockholms län": ["Botkyrka","Danderyd","Ekerö","Haninge","Huddinge","Järfälla","Lidingö","Nacka","Norrtälje","Nykvarn","Nynäshamn","Salem","Sigtuna","Sollentuna","Solna","Stockholm","Sundbyberg","Södertälje","Tyresö","Täby","Upplands Väsby","Upplands-Bro","Vallentuna","Vaxholm","Värmdö","Österåker"],
  "Södermanlands län": ["Eskilstuna","Flen","Gnesta","Katrineholm","Nyköping","Oxelösund","Strängnäs","Trosa","Vingåker"],
  "Uppsala län": ["Enköping","Heby","Håbo","Knivsta","Tierp","Uppsala","Älvkarleby","Östhammar"],
  "Värmlands län": ["Arvika","Eda","Filipstad","Forshaga","Grums","Hagfors","Hammarö","Karlstad","Kil","Kristinehamn","Munkfors","Storfors","Sunne","Säffle","Torsby","Årjäng"],
  "Västerbottens län": ["Bjurholm","Dorotea","Lycksele","Malå","Nordmaling","Norsjö","Robertsfors","Skellefteå","Sorsele","Storuman","Umeå","Vilhelmina","Vindeln","Vännäs","Åsele"],
  "Västernorrlands län": ["Härnösand","Kramfors","Sollefteå","Sundsvall","Timrå","Ånge","Örnsköldsvik"],
  "Västmanlands län": ["Arboga","Fagersta","Hallstahammar","Köping","Kungsör","Norberg","Sala","Skinnskatteberg","Surahammar","Västerås"],
  "Västra Götalands län": ["Ale","Alingsås","Bengtsfors","Bollebygd","Borås","Dals-Ed","Essunga","Falköping","Färgelanda","Grästorp","Gullspång","Göteborg","Götene","Herrljunga","Hjo","Härryda","Karlsborg","Kungälv","Lerum","Lidköping","Lilla Edet","Lysekil","Mariestad","Mark","Mellerud","Munkedal","Mölndal","Orust","Partille","Skara","Skövde","Sotenäs","Stenungsund","Strömstad","Svenljunga","Tanum","Tibro","Tidaholm","Tjörn","Tranemo","Trollhättan","Töreboda","Uddevalla","Ulricehamn","Vara","Vårgårda","Vänersborg","Åmål","Öckerö"],
  "Örebro län": ["Askersund","Degerfors","Hallsberg","Hällefors","Karlskoga","Kumla","Laxå","Lekeberg","Lindesberg","Ljusnarsberg","Nora","Örebro"],
  "Östergötlands län": ["Boxholm","Finspång","Kinda","Linköping","Mjölby","Motala","Norrköping","Söderköping","Vadstena","Valdemarsvik","Ydre","Åtvidaberg","Ödeshög"]
};

// Källa: Arbetsförmedlingens "Hitta yrken" (samtliga 21 officiella yrkesområden). Varje område listar dess officiella yrkesgrupper (SSYK4-nivå).
export const YRKESOMRADEN = {
  "Administration, ekonomi, juridik": ["Advokater","Affärs- och företagsjurister","Arbetsförmedlare","Arkeologer och specialister inom humaniora m.m.","Arkiv- och biblioteksassistenter m.fl.","Backofficepersonal m.fl.","Banktjänstemän","Chefssekreterare och VD-assistenter m.fl.","Controller","Domare","Domstols- och juristsekreterare m.fl.","Ekonomiassistenter m.fl.","Finansanalytiker och investeringsrådgivare m.fl.","Försäkringssäljare och försäkringsrådgivare","Förvaltnings- och organisationsjurister","Gruppledare för kontorspersonal","Informatörer, kommunikatörer och PR-specialister","Inkasserare och pantlånare m.fl.","Kontorsreceptionister","Kundtjänstpersonal","Lantmätare","Lednings- och organisationsutvecklare","Löne- och personaladministratörer","Medicinska sekreterare, vårdadministratörer m.fl.","Mäklare inom finans","Nationalekonomer och makroanalytiker m.fl.","Personal- och HR-specialister","Planerare och utredare m.fl.","Redovisningsekonomer","Revisorer m.fl.","Skadereglerare och värderare","Skattehandläggare","Skolassistenter m.fl.","Socialförsäkringshandläggare","Statistiker","Telefonister","Traders och fondförvaltare","Åklagare","Övriga ekonomer","Övriga handläggare","Övriga jurister","Övriga kontorsassistenter och sekreterare"],
  "Bygg och anläggning": ["Anläggningsarbetare","Anläggningsdykare","Anläggningsmaskinförare m.fl.","Arbetsledare inom bygg, anläggning och gruva","Betongarbetare","Brunnsborrare m.fl.","Byggnads- och ventilationsplåtslagare","Civilingenjörsyrken inom bygg och anläggning","Golvläggare","Grovarbetare inom bygg och anläggning","Gruv- och stenbrottsarbetare","Ingenjörer och tekniker inom bygg och anläggning","Isoleringsmontörer","Kranförare m.fl.","Kyl- och värmepumpstekniker m.fl.","Murare m.fl.","Målare","Ställningsbyggare","Takmontörer","Träarbetare, snickare m.fl.","VVS-montörer m.fl.","Övriga byggnads- och anläggningsarbetare"],
  "Chefer och verksamhetsledare": ["Chefer inom arkitekt- och ingenjörsverksamhet","Chefer inom bank, finans och försäkring","Chefer inom friskvård, sport och fritid","Chefer inom förskoleverksamhet","Chefer inom grund- och gymnasieskola samt vuxenutbildning","Chefer inom handel","Chefer inom hälso- och sjukvård","Chefer inom socialt och kurativt arbete","Chefer inom äldreomsorg","Chefer och ledare inom trossamfund","Chefstjänstemän i intresseorganisationer","Driftchefer inom bygg, anläggning och gruva","Ekonomi- och finanschefer","Fastighets- och förvaltningschefer","Forsknings- och utvecklingschefer","Försäljnings- och marknadschefer","Förvaltare inom skogsbruk och lantbruk m.fl.","Förvaltnings- och planeringschefer","General-, landstings- och kommundirektörer m.fl.","Hotell- och konferenschefer","IT-chefer","Informations-, kommunikations- och PR-chefer","Inköps-, logistik- och transportchefer","Personal- och HR-chefer","Politiker","Produktionschefer inom tillverkning","Restaurang- och kökschefer","Verkställande direktörer m.fl.","Övriga administrations- och servicechefer","Övriga chefer inom samhällsservice","Övriga chefer inom utbildning","Övriga chefer inom övrig servicenäring"],
  "Data/IT": ["Drifttekniker, IT","IT-säkerhetsspecialister","Mjukvaru- och systemutvecklare m.fl.","Nätverks- och systemtekniker m.fl.","Supporttekniker, IT","Systemadministratörer","Systemanalytiker och IT-arkitekter m.fl.","Systemförvaltare m.fl.","Systemtestare och testledare","Utvecklare inom spel och digitala media","Webbmaster och webbadministratörer","Övriga IT-specialister"],
  "Försäljning, inköp, marknadsföring": ["Apotekstekniker","Bensinstationspersonal","Butikssäljare, dagligvaror","Butikssäljare, fackhandel","Evenemangs- och reseproducenter m.fl.","Eventsäljare och butiksdemonstratörer m.fl.","Fastighetsmäklare","Företagssäljare","Guider och reseledare","Inköpare och upphandlare","Inköps- och orderassistenter","Kassapersonal m.fl.","Marknads- och försäljningsassistenter","Marknadsanalytiker och marknadsförare m.fl.","Marknadsundersökare och intervjuare","Optikerassistenter","Ordersamordnare m.fl.","Resesäljare och trafikassistenter m.fl.","Speditörer och transportmäklare","Säljande butikschefer och avdelningschefer i butik","Telefonförsäljare m.fl.","Torg- och marknadsförsäljare m.fl.","Uthyrare","Övriga förmedlare"],
  "Hantverk": ["Bagare och konditorer","Fin-, inrednings- och möbelsnickare","Finmekaniker","Glastekniker","Guld- och silversmeder","Läderhantverkare och skomakare","Manuella ytbehandlare, trä","Musikinstrumentmakare och övriga konsthantverkare","Skräddare och ateljésömmerskor m.fl.","Smeder","Sömmare","Tapetserare"],
  "Hotell, restaurang, storhushåll": ["Bartendrar","Croupierer och oddssättare m.fl.","Hotellreceptionister m.fl.","Hovmästare och servitörer","Kafé- och konditoribiträden","Kockar och kallskänkor","Köksmästare och souschefer","Pizzabagare m.fl.","Restaurang- och köksbiträden m.fl.","Storhushållsföreståndare"],
  "Hälso- och sjukvård": ["AT-läkare","Ambulanssjuksköterskor m.fl.","Ambulanssjukvårdare","Anestesisjuksköterskor","Apotekare","Arbetsterapeuter","Audionomer och logopeder","Barnmorskor","Barnsjuksköterskor","Barnsköterskor","Dietister","Distriktssköterskor","Djursjukskötare m.fl.","Fysioterapeuter och sjukgymnaster","Företagssköterskor","Geriatriksjuksköterskor","Grundutbildade sjuksköterskor","Intensivvårdssjuksköterskor","Kiropraktorer och naprapater m.fl.","Operationssjuksköterskor","Optiker","Psykiatrisjuksköterskor","Psykologer","Psykoterapeuter","Receptarier","Röntgensjuksköterskor","ST-läkare","Skolsköterskor","Skötare","Specialistläkare","Tandhygienister","Tandläkare","Tandsköterskor","Terapeuter inom alternativmedicin","Undersköterskor, hemtjänst, hemsjukvård, äldreboende och habilitering","Undersköterskor, vård- och specialavdelning och mottagning","Veterinärer","Vårdbiträden","Övrig vård- och omsorgspersonal","Övriga läkare","Övriga specialister inom hälso- och sjukvård","Övriga specialistsjuksköterskor"],
  "Industriell tillverkning": ["Arbetsledare inom tillverkning","Bergsprängare","Bokbindare m.fl.","Fordonsmontörer","Gjutare","Handpaketerare och andra fabriksarbetare","Lackerare och industrimålare","Maskinoperatörer inom ytbehandling, trä","Maskinoperatörer, blekning, färgning och tvättning","Maskinoperatörer, cement-, sten- och betongvaror","Maskinoperatörer, farmaceutiska produkter","Maskinoperatörer, gummiindustri","Maskinoperatörer, kemisktekniska och fotografiska produkter","Maskinoperatörer, kvarn-, bageri- och konfektyrindustri","Maskinoperatörer, kött- och fiskberedningsindustri","Maskinoperatörer, mejeri","Maskinoperatörer, pappersvaruindustri","Maskinoperatörer, plastindustri","Maskinoperatörer, påfyllning, packning och märkning","Maskinoperatörer, ytbehandling","Maskinsnickare och maskinoperatörer, träindustri","Maskinställare och maskinoperatörer, metallarbete","Montörer, elektrisk och elektronisk utrustning","Montörer, metall-, gummi- och plastprodukter","Montörer, träprodukter","Operatörer inom sågverk, hyvleri och plywood m.m.","Prepresstekniker","Processoperatörer, papper","Processoperatörer, pappersmassa","Processoperatörer, stenkross- och malmförädling","Provsmakare och kvalitetsbedömare","Slaktare och styckare m.fl.","Slipare m.fl.","Stenhuggare m.fl.","Stålkonstruktionsmontörer och grovplåtsslagare","Svetsare och gasskärare","Tryckare","Tunnplåtslagare","Valsverksoperatörer","Verktygsmakare","Övriga maskin- och processoperatörer vid stål- och metallverk","Övriga maskinoperatörer, livsmedelsindustri m.m.","Övriga maskinoperatörer, textil-, skinn- och läderindustri","Övriga montörer","Övriga process- och maskinoperatörer"],
  "Installation, drift, underhåll": ["Distributionselektriker","Drifttekniker vid värme- och vattenverk","Elektronikreparatörer och kommunikationselektriker m.fl.","Fastighetsskötare","Flygmekaniker m.fl.","Industrielektriker","Installations- och serviceelektriker","Motorfordonsmekaniker och fordonsreparatörer","Processövervakare, kemisk industri","Processövervakare, metallproduktion","Underhållsmekaniker och maskinreparatörer","Vaktmästare m.fl.","Övriga drifttekniker och processövervakare","Övriga servicearbetare"],
  "Kropps- och skönhetsvård": ["Fotterapeuter","Frisörer","Hudterapeuter","Massörer och massageterapeuter","Övriga skönhets- och kroppsterapeuter"],
  "Kultur, media, design": ["Bibliotekarier och arkivarier","Bild- och sändningstekniker","Bildkonstnärer m.fl.","Designer inom spel och digitala medier","Fotografer","Författare m.fl.","Grafiska formgivare m.fl.","Industridesigner","Inredare, dekoratörer och scenografer m.fl.","Inspicienter och scriptor m.fl.","Journalister m.fl.","Koreografer och dansare","Ljus-, ljud- och scentekniker","Museiintendenter m.fl.","Musiker, sångare och kompositörer","Regissörer och producenter av film, teater m.m.","Skådespelare","Översättare, tolkar och lingvister m.fl.","Övriga designer och formgivare","Övriga yrken inom kultur och underhållning"],
  "Militära yrken": ["Officerare","Soldater m.fl.","Specialistofficerare"],
  "Naturbruk": ["Bärplockare och plantörer m.fl.","Fiskare","Fiskodlare","Förare av jordbruks- och skogsmaskiner","Odlare av jordbruksväxter, frukt och bär","Skogsarbetare","Specialister och rådgivare inom lantbruk m.m.","Specialister och rådgivare inom skogsbruk","Trädgårdsanläggare m.fl.","Trädgårdsodlare","Uppfödare och skötare av lantbrukets husdjur","Uppfödare och skötare av sällskapsdjur","Växtodlare och djuruppfödare, blandad drift","Övriga djuruppfödare och djurskötare"],
  "Naturvetenskap": ["Kemist","Biolog","Fysiker","Matematiker","Geolog","Meteorolog","Biomedicinsk analytiker/BMA","Miljöinspektör","Miljösamordnare/Miljökoordinator","Miljöingenjör/Miljövårdsingenjör","Toxikolog","Mikrobiolog","Genetiker","Zoolog","Marinbiolog","Ekolog","Hydrolog","Naturvärdesinventerare","Livsmedelsinspektör","Astronom"],
  "Pedagogik": ["Barnskötare","Doktorander","Elevassistenter m.fl.","Forskarassistenter m.fl.","Fritidspedagoger","Förskollärare","Grundskollärare","Gymnasielärare","Idrottstränare och instruktörer m.fl.","Lärare i yrkesämnen","Professionella idrottsutövare","Professorer","Speciallärare och specialpedagoger m.fl.","Studie- och yrkesvägledare","Trafiklärare","Universitets- och högskolelektorer","Övriga pedagoger med teoretisk specialistkompetens","Övriga universitets- och högskolelärare","Övriga utbildare och instruktörer"],
  "Sanering och renhållning": ["Bilrekonditionerare, fönsterputsare m.fl.","Renhållnings- och återvinningsarbetare","Saneringsarbetare m.fl.","Skorstensfejare","Städare","Städledare och husfruar","Övrig hemservicepersonal m.fl."],
  "Säkerhet och bevakning": ["Arbetsmiljöingenjörer, yrkes- och miljöhygieniker","Brandingenjörer och byggnadsinspektörer m.fl.","Brandmän","Kriminalvårdare","Poliser","SOS-operatörer m.fl.","Säkerhetsinspektörer m.fl.","Tull- och kustbevakningstjänstemän","Väktare och ordningsvakter","Övrig bevaknings- och säkerhetspersonal"],
  "Transport, distribution, lager": ["Arbetsledare inom lager och terminal","Bangårdspersonal","Brevbärare och postterminalarbetare","Buss- och spårvagnsförare","Fartygsbefäl m.fl.","Flygledare","Hamnarbetare","Kabinpersonal m.fl.","Lager- och terminalpersonal","Lastbilsförare m.fl.","Lokförare","Maskinbefäl","Matroser och jungmän m.fl.","Piloter m.fl.","Ramppersonal, flyttkarlar och varupåfyllare m.fl.","Reklamutdelare och tidningsdistributörer","Taxiförare m.fl.","Transportledare och transportsamordnare","Truckförare","Tågvärdar och ombordansvariga m.fl.","Övriga bil-, motorcykel- och cykelförare"],
  "Yrken med social inriktning": ["Begravnings- och krematoriepersonal","Behandlingsassistenter och socialpedagoger m.fl.","Biståndsbedömare m.fl.","Diakoner","Friskvårdskonsulenter och hälsopedagoger m.fl.","Fritidsledare m.fl.","Kuratorer","Pastorer m.fl.","Personliga assistenter","Präster","Socialsekreterare","Vårdare, boendestödjare","Övrig servicepersonal","Övriga yrken inom socialt arbete"],
  "Yrken med teknisk inriktning": ["Arkitekter m.fl.","Civilingenjörsyrken inom elektroteknik","Civilingenjörsyrken inom gruvteknik och metallurgi","Civilingenjörsyrken inom kemi och kemiteknik","Civilingenjörsyrken inom logistik och produktionsplanering","Civilingenjörsyrken inom maskinteknik","Fastighetsförvaltare","Flygtekniker","GIS- och kartingenjörer","Ingenjörer och tekniker inom elektroteknik","Ingenjörer och tekniker inom gruvteknik och metallurgi","Ingenjörer och tekniker inom industri, logistik och produktionsplanering","Ingenjörer och tekniker inom kemi och kemiteknik","Ingenjörer och tekniker inom maskinteknik","Laboratorieingenjörer","Landskapsarkitekter","Planeringsarkitekter m.fl.","Tandtekniker och ortopedingenjörer m.fl.","Tekniker, bilddiagnostik och medicinteknisk utrustning","Övriga civilingenjörsyrken","Övriga ingenjörer och tekniker"]
};

export const FILTER_DEFS = {
  focus:{ label:"Fokusområde", options:Object.keys(YRKESOMRADEN) },
  service:{ label:"Tjänst", options:["Bemanning","Rekrytering","Interim"] },
  sizeBand:{ label:"Storlek (medarbetare)", options:["Litet","Medel","Stort"] }
};
